### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by mekkim** [MITDDC/zork#1]
Is there a license for this source code?  Is it open source?  A license statement would be greatly appreciated so that we know what kind of use is permitted.  Thanks!

**Comment by larsbrinkhoff** [comment]
I'm hoping the MIT license would be appropriate.

There's also precedent for the GPL, which has been used for parts of ITS:  
https://groups.csail.mit.edu/mac/ftpdir/its/

**Comment by 36bit** [comment]
Although MIT has not said anything we can probably draw our own conclusions based on the known history of Zork while taking into consideration the information from https://copyright.cornell.edu/publicdomain specifically,

> 1925 through 1977: Published without a copyright notice

**Comment by jfcarrano** [comment]
The ownership status of these files is not entirely clear. To the extent that MIT holds rights in these files, we are happy to support their broad public use. Any questions about permissions should be directed to permissions-lib@mit.edu. I've added this information to the readme as well.
