### ISSUE TITLE
What, no xyzzy?

### ISSUE THREAD

**Issue by srnelson** [MITDDC/zork#3]
You really need to have an xyzzy in there!

**Comment by larsbrinkhoff** [comment]
Xyzzy is more of an Adventure thing.

**Comment by ljharb** [comment]
It absolutely works in Zork, as an easter egg for Adventure.

**Comment by larsbrinkhoff** [comment]
1979 and 1981 Zork will respond with an insult.

1977 Zork does not have have xyzzy in its vocabulary.
